-- Drop existing tables if re-running
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS outlets;

-- 1. Create Outlets Table
CREATE TABLE outlets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT NOT NULL DEFAULT 'Nagpur'
);

-- 2. Create Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id BIGINT REFERENCES outlets(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    status TEXT CHECK (status IN ('COMPLETED', 'CANCELLED')) DEFAULT 'COMPLETED',
    created_at DATE DEFAULT CURRENT_DATE
);

-- 3. Insert Nagpur Outlets
INSERT INTO outlets (id, name, city) VALUES 
(1, 'Friends Colony', 'Nagpur'),
(2, 'Hazari Pahad', 'Nagpur'),
(3, 'Gokulpeth', 'Nagpur'),
(4, 'Hingna', 'Nagpur');

-- 4. Insert Sample Orders for Testing
-- Friends Colony: Total = 1500 (Low sales -> Triggers Alert)
INSERT INTO orders (outlet_id, amount, status, created_at) VALUES 
(1, 500, 'COMPLETED', '2026-09-27'),
(1, 1000, 'COMPLETED', '2026-09-27');

-- Hazari Pahad: Total = 12000 (Normal)
INSERT INTO orders (outlet_id, amount, status, created_at) VALUES 
(2, 4000, 'COMPLETED', '2026-09-27'),
(2, 8000, 'COMPLETED', '2026-09-27');

-- Gokulpeth: Total = 8500 (Normal)
INSERT INTO orders (outlet_id, amount, status, created_at) VALUES 
(3, 3500, 'COMPLETED', '2026-09-27'),
(3, 5000, 'COMPLETED', '2026-09-27');

-- Hingna: Total = 2200 (Low sales -> Triggers Alert)
INSERT INTO orders (outlet_id, amount, status, created_at) VALUES 
(4, 1000, 'COMPLETED', '2026-09-27'),
(4, 1200, 'COMPLETED', '2026-09-27');
